### PR TITLE
DB Refactor/cleanup

### PR DESCRIPTION
**Pull request by ph0t0shop**

### CODE REVIEW

**Comment by yitzy299** [comment]
Not immediately a major fan - the DB results are then sorted incorrectly (ODER BY time DESC)

**Comment by ph0t0shop** [comment]
> 
> 
> Not immediately a major fan - the DB results are then sorted incorrectly (ODER BY time DESC)

whoops, that can be easily fixed. I'll do that rn

**Comment by yitzy299** [comment]
thanks

**Comment by ph0t0shop** [comment]
done

**Comment by yitzy299** [comment]
looks good

**Comment by ph0t0shop** [comment]
nice, thanks. in the future I could also add support for wildcards ("?") in the suffix, for pagination for example

**Pull request merged**
